/* Write a program to play a game with computer e.g. Slot Machine.*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>

void game_play();
void points_table();

unsigned int token = 3;

int main()
{
    unsigned int options;

    printf("WELCOME to!...\n");
    printf("****************************************\n");
    printf("*             SLOT MACHINE!            *\n");
    printf("****************************************\n");

    printf("PRESS 0 to START the GAME!...\n");
    printf("PRESS any Key to QUIT the GAME!...\n");
    printf("After entering the game you cannot QUIT the GAME!...\n");
    scanf("%d", &options);

    switch (options)
    {
    case 0:
    {
        printf("*********************************************************************************\n");
        printf("** RULES OF THE GAME!. **\n\n");
        printf("INITIALLY YOU WILL BE GIVEN 3 TOKENS!.\n");
        printf("EACH TIME YOU PLAY, YOU LOOSE 1 TOKEN!.\n");
        printf("THERE WILL BE 3 RANDOM NUMBERS GENERATED BY THE COMPUTER!.\n");
        printf("IF ALL 3 RANDOM NUMBERS ARE SAME YOU WILL RECEIVE A JACKOT!.\n");
        printf("IF TWO ARE EQUAL YOU WILL RECEIVE 1 MORE TOKEN TO THE REMAINING TOKEN!.\n");
        printf("IF NONE ARE EQUAL YOU WILL LOOSE 1 TOKEN!.\n");
        printf("*********************************************************************************\n");

        game_play();

        break;
    }
    default:
        printf("EXITING...");
        break;
    }

    return 0;
}

void game_play()
{
    unsigned int rand_num1, rand_num2, rand_num3, i;
    srand(time(0));

    for (i = 0; i < token; i++)
    {
        rand_num1 = rand() % 3 + 1;
        rand_num2 = rand() % 3 + 1;
        rand_num3 = rand() % 3 + 1;

        Sleep(3000);

        printf("NUMBERS GENERATED: \t%d\t%d\t%d\n", rand_num1, rand_num2, rand_num3);

        if (rand_num1 == rand_num2 && rand_num2 == rand_num3)
        {
            printf("******************************\n");
            printf("*    JACKPOT...  YOU WON!    *\n");
            printf("******************************\n");

            break;
        }
        else if (rand_num1 == rand_num2 || rand_num2 == rand_num3)
        {
            token++;
            points_table(i);
        }
        else
        {
            token--;
            printf("Sorry, better luck next time!.\n");
            points_table(i);
        }
    }
}

void points_table(unsigned int i)
{
    printf("+---------------------------------+\n");
    printf("|        TOKENs REMAINING         |\n");
    printf("+---------------------------------+\n");
    printf("|                %d                |\n", token - i);
    printf("+---------------------------------+\n");
}